export { EventBus, globalEventBus } from './event-bus';
export { ProjectManager, projectManager } from './project-manager';
export { DebugService, debugService, setNativeBridge, getNativeBridge } from './debug-service';
export type { StartDebugOptions, NativeBridge } from './debug-service';
export { DebugWebSocketClient, debugWebSocketClient } from './debug-client';
export { MonitorService, monitorService } from './monitor-service';
export { BuildService, buildService } from './build-service';
export { DocService, docService } from './doc-service';
export { PluginManager, pluginManager } from './plugin-manager';
export type { PluginPermission, PluginPermissions, PluginDependency, PluginLoadOptions } from './plugin-manager';
export { PlatformService, platformService } from './platform-service';
export { SnippetService, snippetService } from './snippet-service';
export { FormatService, formatService } from './format-service';
export { WatchService, watchService } from './watch-service';
export { CallStackService, callStackService } from './callstack-service';
export type { StackFrame, CallStack } from './callstack-service';
export { ThemeService, themeService } from './theme-service';
export type { Theme, ThemeType, ThemeColors } from './theme-service';
export { PluginMarketService, pluginMarketService } from './plugin-market-service';
export type { Plugin, PluginManifest, PluginInstallation, PluginSearchOptions, PluginVersion, PluginSearchResult, PluginCategory, InstallOptions, UpdateInfo } from './plugin-market-service';
export { PluginSandboxService, pluginSandboxService } from './plugin-sandbox-service';
export type { PluginSandboxOptions, PluginRuntime } from './plugin-sandbox-service';
export { PluginSandbox, pluginSandbox } from './plugin-sandbox';
export type { SandboxType, SandboxPermissions, SandboxOptions, SandboxMessage, SandboxRuntime, SandboxAPIMethod } from './plugin-sandbox';
export { TemplateService, templateService } from './template-service';
export type { ProjectTemplate, TemplateCategory, TemplateSearchOptions, TemplateSearchResult, VirtualFile, CreateProjectOptions, CreatedProject } from './template-service';
export { ResponsiveService, responsiveService } from './responsive-service';
export type { DeviceType, Breakpoints, ViewportInfo } from './responsive-service';
export { ShortcutService, shortcutService } from './shortcut-service';
export type { Shortcut, KeyboardEventData } from './shortcut-service';
export { CommandPaletteService, commandPaletteService } from './command-palette-service';
export type { Command, CommandMatch } from './command-palette-service';
export { AnimationService, animationService } from './animation-service';
export type { AnimationConfig, AnimationKeyframes } from './animation-service';
export { LazyLoadService, lazyLoadService } from './lazy-load-service';
export type { LazyLoadOptions, ModuleLoadResult } from './lazy-load-service';
export { VirtualListService, virtualListService } from './virtual-list-service';
export type { VirtualListOptions, VirtualListItem } from './virtual-list-service';
export { WebWorkerService, webWorkerService } from './web-worker-service';
export type { WorkerMessage, WorkerTask } from './web-worker-service';
export { OfficialPluginsService, officialPluginsService } from './official-plugins-service';
export type { OfficialPlugin } from './official-plugins-service';
export { CloudSyncService, cloudSyncService } from './cloud-sync-service';
export type { SyncConfig, SyncItem, SyncConflict } from './cloud-sync-service';
export { TeamService, teamService } from './team-service';
export type { TeamMember, Team, Permission, ProjectPermission } from './team-service';
export { TemplateMarketService, templateMarketService } from './template-market-service';
export type { TemplateRating, TemplateDownload } from './template-market-service';
export { PWAService, pwaService } from './pwa-service';
export type { PWAConfig, PWAIcon, InstallPromptEvent } from './pwa-service';
export { CLIService, cliService } from './cli-service';
export type { CLICommand, CLIArgument, CLIOption } from './cli-service';

// v0.3.0+ 新增模块
export * from './engines';
export * from './ai';
export * from './collab';
export * from './platform';
export * from './perf';

// 官方插件
export * from './plugins';